### ISSUE TITLE
com.android.phone keep crash

### ISSUE THREAD

**Issue by marulitua** [kbc-developers/android_kernel_htc_m7wlj#6]
SIM toolkit doesn't work on all nougat based ROM. I have tried all nougat based ROM since last year.
My phone cannot detect the sim card and every time i open network setting com.android.phone always crash.

http://sprunge.us/RIac

What should i do ?
Any response is greatly appreciated.

**Comment by tako0910** [comment]
Please try removing this line from /system/build.prop
`telephony.lteOnCdmaDevice=1`

**Comment by marulitua** [comment]
It works thanks, sensei.
